const state={url:sessionStorage.getItem('slkUrl')||'https://slk-alert-worker.abidogundamilola.workers.dev',key:sessionStorage.getItem('slkAdminKey')||'',alerts:[]};
const $=id=>document.getElementById(id);
$('apiUrl').value=state.url;$('adminKey').value=state.key;

document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.tab).classList.add('active')}));
$('connectBtn').addEventListener('click',connect);$('refreshBtn').addEventListener('click',loadAll);$('alertFilter').addEventListener('change',renderAlerts);
async function api(path){const r=await fetch(state.url.replace(/\/$/,'')+path,{headers:{Authorization:`Bearer ${state.key}`}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function connect(){state.url=$('apiUrl').value.trim();state.key=$('adminKey').value.trim();sessionStorage.setItem('slkUrl',state.url);sessionStorage.setItem('slkAdminKey',state.key);await loadAll()}
async function loadAll(){setStatus('Loading…','muted');$('error').hidden=true;try{const [health,stats,alerts]=await Promise.all([api('/health'),api('/stats'),api('/alerts?limit=200')]);state.alerts=alerts;renderHealth(health);renderStats(stats);renderAlerts();setStatus('Connected','ok')}catch(e){setStatus('Connection failed','bad');$('error').textContent=e.message;$('error').hidden=false}}
function setStatus(text,kind){$('statusText').textContent=text;$('statusDot').className=`dot ${kind}`}
function renderHealth(h){$('mode').textContent=String(h.mode||'—').toUpperCase();$('workerName').textContent=h.service||'—';$('lastResponse').textContent=new Date().toLocaleTimeString();$('pairs').textContent=(h.pairs||[]).join(' · ')||'—';$('healthPill').textContent=h.ok?'healthy':'degraded';$('healthPill').className=`pill ${h.ok?'green':'gray'}`;$('healthDetails').innerHTML=`<div class="health-item"><span>Service</span><strong>${esc(h.service||'—')}</strong></div><div class="health-item"><span>Entry timeframes</span><strong>${esc((h.entryTfs||[]).join(' · ')||'—')}</strong></div><div class="health-item"><span>Server time</span><strong>${esc(h.time||'—')}</strong></div>`}
function renderStats(s){$('total').textContent=s.total??'—';$('open').textContent=s.open??'—';$('tp').textContent=s.tp??'—';$('sl').textContent=s.sl??'—';$('expired').textContent=s.expired??'—';$('winRate').textContent=s.winRate==null?'—':`${(s.winRate*100).toFixed(1)}%`}
function renderAlerts(){const filter=$('alertFilter').value;const rows=state.alerts.filter(a=>filter==='all'||a.status===filter);if(!rows.length){$('alertsList').innerHTML='<div class="empty">No alerts match this filter, or the Worker is not connected.</div>';return}$('alertsList').innerHTML=rows.map(a=>`<div class="alert-row"><div><strong>${esc(a.pair)} · ${esc(a.tf)} · ${esc(a.direction)}</strong><small>${esc(a.keyLevel||'')} · ${fmtDate(a.candleCloseTime)}</small></div><div><span>Entry</span><strong>${num(a.entry)}</strong></div><div><span>SL / TP1</span><strong>${num(a.stopLoss)} / ${num(a.tp1)}</strong></div><div><span>Status</span><strong class="state ${a.status==='SL_HIT'?'loss':''}">${esc(a.status)} · ${esc(a.alertStatus)}</strong></div></div>`).join('')}
function num(x){return x==null?'—':Number(x).toPrecision(7)}function fmtDate(x){if(!x)return'—';const d=new Date(x);return Number.isNaN(d.getTime())?'—':d.toISOString().slice(0,16).replace('T',' ')+' UTC'}function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
